org: velei
service: quiztopia

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    JWT_SECRET: hemlis
    DYNAMODB_TABLE: quiztopia
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/quiztopia"
            - "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/quiztopia/index/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  signup:
    handler: auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post

  createQuiz:
    handler: functions/quiz/createQuiz.handler
    events:
      - httpApi:
          path: /quiz
          method: post

  testAuth:
    handler: auth/testAuth.handler
    events:
      - httpApi:
          path: /auth/test
          method: get

  login:
    handler: auth/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: post

  getAllQuizzes:
    handler: functions/quiz/getAllQuizzes.handler
    events:
      - httpApi:
          path: /quiz
          method: get

  addQuestion:
    handler: functions/quiz/addQuestion.handler
    events:
      - httpApi:
          path: /quiz/question
          method: post

  getQuizById:
    handler: functions/quiz/getQuizById.handler
    events:
      - httpApi:
          path: /quiz/{userId}/{quizId}
          method: get

  deleteQuiz:
    handler: functions/quiz/deleteQuiz.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: delete

resources:
  Resources:
    QuiztopiaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quiztopia
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
